// <auto-generated />
using Budgetting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Budgetting.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221115042639_AddedExpenseFields")]
    partial class AddedExpenseFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Budgetting.Models.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("MonthlyCarInsurance")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyCarPayment")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyCreditCard")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyFood")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyHealthInsurance")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyInvesting")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyRecreation")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyRentAndUtilities")
                        .HasColumnType("float");

                    b.Property<double>("MonthlySaving")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyStudentLoan")
                        .HasColumnType("float");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<double>("YearlyGrossIncome")
                        .HasColumnType("float");

                    b.Property<double>("YearlyInterestAndDividendIncome")
                        .HasColumnType("float");

                    b.Property<double>("YearlyOtherIncome")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("Budgetting.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Budgetting.Models.Budget", b =>
                {
                    b.HasOne("Budgetting.Models.Profile", null)
                        .WithOne("Budget")
                        .HasForeignKey("Budgetting.Models.Budget", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
